# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestMagUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GestMag_WINDOW(object):
    def setupUi(self, GestMag_WINDOW):
        GestMag_WINDOW.setObjectName("GestMag_WINDOW")
        GestMag_WINDOW.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GestMag_WINDOW.sizePolicy().hasHeightForWidth())
        GestMag_WINDOW.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GestMag_WINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_mainWindow = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_mainWindow.setObjectName("tab_mainWindow")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbl_storage = QtWidgets.QTableWidget(self.tab_view)
        self.tbl_storage.setObjectName("tbl_storage")
        self.tbl_storage.setColumnCount(0)
        self.tbl_storage.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tbl_storage)
        self.tab_mainWindow.addTab(self.tab_view, "")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.tab_mainWindow.addTab(self.tab_control, "")
        self.tab_manual = QtWidgets.QWidget()
        self.tab_manual.setObjectName("tab_manual")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_manual)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_manual)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbl_blockView = QtWidgets.QTableWidget(self.groupBox_4)
        self.tbl_blockView.setShowGrid(True)
        self.tbl_blockView.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_blockView.setWordWrap(True)
        self.tbl_blockView.setRowCount(3)
        self.tbl_blockView.setColumnCount(3)
        self.tbl_blockView.setObjectName("tbl_blockView")
        self.tbl_blockView.horizontalHeader().setVisible(False)
        self.tbl_blockView.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_blockView.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_blockView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tbl_blockView)
        self.btn_createStorage = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_createStorage.setObjectName("btn_createStorage")
        self.verticalLayout_3.addWidget(self.btn_createStorage)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.grp_block = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_block.setObjectName("grp_block")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_block)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_blockID = QtWidgets.QLineEdit(self.grp_block)
        self.txt_blockID.setObjectName("txt_blockID")
        self.gridLayout_2.addWidget(self.txt_blockID, 1, 1, 1, 2)
        self.btn_genID = QtWidgets.QPushButton(self.grp_block)
        self.btn_genID.setObjectName("btn_genID")
        self.gridLayout_2.addWidget(self.btn_genID, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.grp_block)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grp_block)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.cmb_matID = QtWidgets.QComboBox(self.grp_block)
        self.cmb_matID.setMaxVisibleItems(10)
        self.cmb_matID.setObjectName("cmb_matID")
        self.gridLayout_2.addWidget(self.cmb_matID, 0, 1, 1, 1)
        self.btn_addBlock = QtWidgets.QPushButton(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addBlock.sizePolicy().hasHeightForWidth())
        self.btn_addBlock.setSizePolicy(sizePolicy)
        self.btn_addBlock.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addBlock.setObjectName("btn_addBlock")
        self.gridLayout_2.addWidget(self.btn_addBlock, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_dimX = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimX.sizePolicy().hasHeightForWidth())
        self.txt_dimX.setSizePolicy(sizePolicy)
        self.txt_dimX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimX.setObjectName("txt_dimX")
        self.horizontalLayout_2.addWidget(self.txt_dimX)
        self.txt_dimY = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimY.sizePolicy().hasHeightForWidth())
        self.txt_dimY.setSizePolicy(sizePolicy)
        self.txt_dimY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimY.setObjectName("txt_dimY")
        self.horizontalLayout_2.addWidget(self.txt_dimY)
        self.txt_dimZ = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimZ.sizePolicy().hasHeightForWidth())
        self.txt_dimZ.setSizePolicy(sizePolicy)
        self.txt_dimZ.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimZ.setObjectName("txt_dimZ")
        self.horizontalLayout_2.addWidget(self.txt_dimZ)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 2, 1, 2)
        self.gridLayout.addWidget(self.grp_block, 0, 1, 1, 1)
        self.grp_recipe = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_recipe.setObjectName("grp_recipe")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grp_recipe)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txt_spCutOriz = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_spCutOriz.setMaximumSize(QtCore.QSize(75, 16777215))
        self.txt_spCutOriz.setInputMask("")
        self.txt_spCutOriz.setText("")
        self.txt_spCutOriz.setMaxLength(32767)
        self.txt_spCutOriz.setPlaceholderText("")
        self.txt_spCutOriz.setObjectName("txt_spCutOriz")
        self.gridLayout_4.addWidget(self.txt_spCutOriz, 2, 7, 1, 1)
        self.txt_spCutVert = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_spCutVert.setMaximumSize(QtCore.QSize(75, 16777215))
        self.txt_spCutVert.setInputMask("")
        self.txt_spCutVert.setText("")
        self.txt_spCutVert.setMaxLength(32767)
        self.txt_spCutVert.setPlaceholderText("")
        self.txt_spCutVert.setObjectName("txt_spCutVert")
        self.gridLayout_4.addWidget(self.txt_spCutVert, 1, 7, 1, 1)
        self.txt_nCutOriz = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_nCutOriz.setMaximumSize(QtCore.QSize(75, 16777215))
        self.txt_nCutOriz.setInputMask("")
        self.txt_nCutOriz.setText("")
        self.txt_nCutOriz.setMaxLength(32767)
        self.txt_nCutOriz.setPlaceholderText("")
        self.txt_nCutOriz.setObjectName("txt_nCutOriz")
        self.gridLayout_4.addWidget(self.txt_nCutOriz, 2, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.grp_recipe)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.grp_recipe)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.grp_recipe)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.txt_nCutVert = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_nCutVert.setMaximumSize(QtCore.QSize(75, 16777215))
        self.txt_nCutVert.setInputMask("")
        self.txt_nCutVert.setText("")
        self.txt_nCutVert.setMaxLength(32767)
        self.txt_nCutVert.setPlaceholderText("")
        self.txt_nCutVert.setObjectName("txt_nCutVert")
        self.gridLayout_4.addWidget(self.txt_nCutVert, 1, 1, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.grp_recipe)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 4, 1, 1)
        self.cmb_matID2 = QtWidgets.QComboBox(self.grp_recipe)
        self.cmb_matID2.setMaxVisibleItems(10)
        self.cmb_matID2.setObjectName("cmb_matID2")
        self.gridLayout_4.addWidget(self.cmb_matID2, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grp_recipe)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 4, 1, 1)
        self.cmb_matID_2 = QtWidgets.QComboBox(self.grp_recipe)
        self.cmb_matID_2.setMaxVisibleItems(10)
        self.cmb_matID_2.setObjectName("cmb_matID_2")
        self.cmb_matID_2.addItem("")
        self.cmb_matID_2.addItem("")
        self.cmb_matID_2.addItem("")
        self.cmb_matID_2.addItem("")
        self.cmb_matID_2.addItem("")
        self.cmb_matID_2.addItem("")
        self.gridLayout_4.addWidget(self.cmb_matID_2, 3, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 4, 1, 1)
        self.btn_addMaterial_2 = QtWidgets.QPushButton(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addMaterial_2.sizePolicy().hasHeightForWidth())
        self.btn_addMaterial_2.setSizePolicy(sizePolicy)
        self.btn_addMaterial_2.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addMaterial_2.setObjectName("btn_addMaterial_2")
        self.gridLayout_4.addWidget(self.btn_addMaterial_2, 4, 1, 1, 8)
        self.gridLayout.addWidget(self.grp_recipe, 1, 0, 1, 1)
        self.grp_material = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_material.setObjectName("grp_material")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grp_material)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_lift = QtWidgets.QLineEdit(self.grp_material)
        self.txt_lift.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_lift.setPlaceholderText("")
        self.txt_lift.setObjectName("txt_lift")
        self.gridLayout_3.addWidget(self.txt_lift, 2, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.grp_material)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grp_material)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.txt_color = QtWidgets.QLineEdit(self.grp_material)
        self.txt_color.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_color.setMaxLength(10)
        self.txt_color.setPlaceholderText("")
        self.txt_color.setObjectName("txt_color")
        self.gridLayout_3.addWidget(self.txt_color, 4, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.grp_material)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.grp_material)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.btn_addMaterial = QtWidgets.QPushButton(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addMaterial.sizePolicy().hasHeightForWidth())
        self.btn_addMaterial.setSizePolicy(sizePolicy)
        self.btn_addMaterial.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addMaterial.setObjectName("btn_addMaterial")
        self.gridLayout_3.addWidget(self.btn_addMaterial, 6, 2, 1, 1)
        self.txt_density = QtWidgets.QLineEdit(self.grp_material)
        self.txt_density.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_density.setPlaceholderText("")
        self.txt_density.setObjectName("txt_density")
        self.gridLayout_3.addWidget(self.txt_density, 3, 1, 1, 2)
        self.tim_restTime = QtWidgets.QTimeEdit(self.grp_material)
        self.tim_restTime.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.tim_restTime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.tim_restTime.setCalendarPopup(False)
        self.tim_restTime.setObjectName("tim_restTime")
        self.gridLayout_3.addWidget(self.tim_restTime, 5, 1, 1, 1)
        self.txt_matID = QtWidgets.QLineEdit(self.grp_material)
        self.txt_matID.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txt_matID.setInputMask("")
        self.txt_matID.setText("")
        self.txt_matID.setMaxLength(32767)
        self.txt_matID.setPlaceholderText("")
        self.txt_matID.setObjectName("txt_matID")
        self.gridLayout_3.addWidget(self.txt_matID, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.grp_material, 0, 0, 1, 1)
        self.tab_mainWindow.addTab(self.tab_manual, "")
        self.horizontalLayout.addWidget(self.tab_mainWindow)
        GestMag_WINDOW.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GestMag_WINDOW)
        self.statusbar.setObjectName("statusbar")
        GestMag_WINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(GestMag_WINDOW)
        self.tab_mainWindow.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(GestMag_WINDOW)
        GestMag_WINDOW.setTabOrder(self.tab_mainWindow, self.txt_lift)
        GestMag_WINDOW.setTabOrder(self.txt_lift, self.txt_density)
        GestMag_WINDOW.setTabOrder(self.txt_density, self.txt_color)
        GestMag_WINDOW.setTabOrder(self.txt_color, self.btn_addMaterial)
        GestMag_WINDOW.setTabOrder(self.btn_addMaterial, self.cmb_matID)
        GestMag_WINDOW.setTabOrder(self.cmb_matID, self.txt_blockID)
        GestMag_WINDOW.setTabOrder(self.txt_blockID, self.btn_genID)
        GestMag_WINDOW.setTabOrder(self.btn_genID, self.txt_dimX)
        GestMag_WINDOW.setTabOrder(self.txt_dimX, self.txt_dimY)
        GestMag_WINDOW.setTabOrder(self.txt_dimY, self.txt_dimZ)
        GestMag_WINDOW.setTabOrder(self.txt_dimZ, self.btn_addBlock)

    def retranslateUi(self, GestMag_WINDOW):
        _translate = QtCore.QCoreApplication.translate
        GestMag_WINDOW.setWindowTitle(_translate("GestMag_WINDOW", "MainWindow"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_view), _translate("GestMag_WINDOW", "Storage"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_control), _translate("GestMag_WINDOW", "Control"))
        self.groupBox_4.setTitle(_translate("GestMag_WINDOW", "GroupBox"))
        self.btn_createStorage.setText(_translate("GestMag_WINDOW", "CreateStorage"))
        self.grp_block.setTitle(_translate("GestMag_WINDOW", "AddBlock"))
        self.txt_blockID.setPlaceholderText(_translate("GestMag_WINDOW", "AAAA"))
        self.btn_genID.setText(_translate("GestMag_WINDOW", "Generate"))
        self.label.setText(_translate("GestMag_WINDOW", "Material_ID"))
        self.label_2.setText(_translate("GestMag_WINDOW", "Block_ID"))
        self.label_3.setText(_translate("GestMag_WINDOW", "Dimension X,Y,Z"))
        self.btn_addBlock.setText(_translate("GestMag_WINDOW", "Add Block"))
        self.txt_dimX.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimY.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimZ.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.grp_recipe.setTitle(_translate("GestMag_WINDOW", "AddRecipe"))
        self.label_9.setText(_translate("GestMag_WINDOW", "Material_ID"))
        self.label_12.setText(_translate("GestMag_WINDOW", "N cut orizz"))
        self.label_10.setText(_translate("GestMag_WINDOW", "N cut vert"))
        self.label_13.setText(_translate("GestMag_WINDOW", "SP cut orizz"))
        self.label_11.setText(_translate("GestMag_WINDOW", "SP cut vert"))
        self.cmb_matID_2.setItemText(0, _translate("GestMag_WINDOW", "FIOR"))
        self.cmb_matID_2.setItemText(1, _translate("GestMag_WINDOW", "OZARI"))
        self.cmb_matID_2.setItemText(2, _translate("GestMag_WINDOW", "OKIN"))
        self.cmb_matID_2.setItemText(3, _translate("GestMag_WINDOW", "CULL"))
        self.cmb_matID_2.setItemText(4, _translate("GestMag_WINDOW", "LOCH"))
        self.cmb_matID_2.setItemText(5, _translate("GestMag_WINDOW", "GALT"))
        self.label_14.setText(_translate("GestMag_WINDOW", "Prog Sagomatura"))
        self.btn_addMaterial_2.setText(_translate("GestMag_WINDOW", "Add Recipe"))
        self.grp_material.setTitle(_translate("GestMag_WINDOW", "AddMaterial"))
        self.txt_lift.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_lift.setText(_translate("GestMag_WINDOW", "0"))
        self.label_8.setText(_translate("GestMag_WINDOW", "restTime"))
        self.label_6.setText(_translate("GestMag_WINDOW", "density"))
        self.txt_color.setText(_translate("GestMag_WINDOW", "0"))
        self.label_7.setText(_translate("GestMag_WINDOW", "color"))
        self.label_5.setText(_translate("GestMag_WINDOW", "lift"))
        self.btn_addMaterial.setText(_translate("GestMag_WINDOW", "Add Material"))
        self.txt_density.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_density.setText(_translate("GestMag_WINDOW", "0"))
        self.tim_restTime.setDisplayFormat(_translate("GestMag_WINDOW", "HH:mm"))
        self.label_4.setText(_translate("GestMag_WINDOW", "Material_ID"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_manual), _translate("GestMag_WINDOW", "Manual"))

