# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestMagUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GestMag_WINDOW(object):
    def setupUi(self, GestMag_WINDOW):
        GestMag_WINDOW.setObjectName("GestMag_WINDOW")
        GestMag_WINDOW.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GestMag_WINDOW.sizePolicy().hasHeightForWidth())
        GestMag_WINDOW.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GestMag_WINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_mainWindow = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_mainWindow.setObjectName("tab_mainWindow")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.tab_view)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.tab_mainWindow.addTab(self.tab_view, "")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.tab_mainWindow.addTab(self.tab_control, "")
        self.tab_manual = QtWidgets.QWidget()
        self.tab_manual.setObjectName("tab_manual")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_manual)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_manual)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_manual)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.grp_material = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_material.setObjectName("grp_material")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grp_material)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_lift = QtWidgets.QLineEdit(self.grp_material)
        self.txt_lift.setPlaceholderText("")
        self.txt_lift.setObjectName("txt_lift")
        self.gridLayout_3.addWidget(self.txt_lift, 1, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.grp_material)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grp_material)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.tim_restTime = QtWidgets.QTimeEdit(self.grp_material)
        self.tim_restTime.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.tim_restTime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.tim_restTime.setCalendarPopup(False)
        self.tim_restTime.setObjectName("tim_restTime")
        self.gridLayout_3.addWidget(self.tim_restTime, 4, 2, 1, 1)
        self.txt_color = QtWidgets.QLineEdit(self.grp_material)
        self.txt_color.setMaxLength(10)
        self.txt_color.setPlaceholderText("")
        self.txt_color.setObjectName("txt_color")
        self.gridLayout_3.addWidget(self.txt_color, 3, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.grp_material)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.grp_material)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.grp_material)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.btn_addMaterial = QtWidgets.QPushButton(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addMaterial.sizePolicy().hasHeightForWidth())
        self.btn_addMaterial.setSizePolicy(sizePolicy)
        self.btn_addMaterial.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addMaterial.setObjectName("btn_addMaterial")
        self.gridLayout_3.addWidget(self.btn_addMaterial, 5, 2, 1, 1)
        self.txt_matID = QtWidgets.QLineEdit(self.grp_material)
        self.txt_matID.setMaxLength(20)
        self.txt_matID.setPlaceholderText("")
        self.txt_matID.setObjectName("txt_matID")
        self.gridLayout_3.addWidget(self.txt_matID, 0, 2, 1, 1)
        self.txt_density = QtWidgets.QLineEdit(self.grp_material)
        self.txt_density.setPlaceholderText("")
        self.txt_density.setObjectName("txt_density")
        self.gridLayout_3.addWidget(self.txt_density, 2, 1, 1, 2)
        self.gridLayout.addWidget(self.grp_material, 0, 0, 1, 1)
        self.grp_block = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_block.setObjectName("grp_block")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_block)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_blockID = QtWidgets.QLineEdit(self.grp_block)
        self.txt_blockID.setObjectName("txt_blockID")
        self.gridLayout_2.addWidget(self.txt_blockID, 1, 1, 1, 2)
        self.btn_genID = QtWidgets.QPushButton(self.grp_block)
        self.btn_genID.setObjectName("btn_genID")
        self.gridLayout_2.addWidget(self.btn_genID, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.grp_block)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grp_block)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.cmb_matID = QtWidgets.QComboBox(self.grp_block)
        self.cmb_matID.setMaxVisibleItems(10)
        self.cmb_matID.setObjectName("cmb_matID")
        self.gridLayout_2.addWidget(self.cmb_matID, 0, 1, 1, 1)
        self.btn_addBlock = QtWidgets.QPushButton(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addBlock.sizePolicy().hasHeightForWidth())
        self.btn_addBlock.setSizePolicy(sizePolicy)
        self.btn_addBlock.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addBlock.setObjectName("btn_addBlock")
        self.gridLayout_2.addWidget(self.btn_addBlock, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_dimX = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimX.sizePolicy().hasHeightForWidth())
        self.txt_dimX.setSizePolicy(sizePolicy)
        self.txt_dimX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimX.setObjectName("txt_dimX")
        self.horizontalLayout_2.addWidget(self.txt_dimX)
        self.txt_dimY = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimY.sizePolicy().hasHeightForWidth())
        self.txt_dimY.setSizePolicy(sizePolicy)
        self.txt_dimY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimY.setObjectName("txt_dimY")
        self.horizontalLayout_2.addWidget(self.txt_dimY)
        self.txt_dimZ = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimZ.sizePolicy().hasHeightForWidth())
        self.txt_dimZ.setSizePolicy(sizePolicy)
        self.txt_dimZ.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimZ.setObjectName("txt_dimZ")
        self.horizontalLayout_2.addWidget(self.txt_dimZ)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 2, 1, 2)
        self.gridLayout.addWidget(self.grp_block, 0, 1, 1, 1)
        self.tab_mainWindow.addTab(self.tab_manual, "")
        self.horizontalLayout.addWidget(self.tab_mainWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        GestMag_WINDOW.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GestMag_WINDOW)
        self.statusbar.setObjectName("statusbar")
        GestMag_WINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(GestMag_WINDOW)
        self.tab_mainWindow.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(GestMag_WINDOW)
        GestMag_WINDOW.setTabOrder(self.tab_mainWindow, self.txt_matID)
        GestMag_WINDOW.setTabOrder(self.txt_matID, self.txt_lift)
        GestMag_WINDOW.setTabOrder(self.txt_lift, self.txt_density)
        GestMag_WINDOW.setTabOrder(self.txt_density, self.txt_color)
        GestMag_WINDOW.setTabOrder(self.txt_color, self.tim_restTime)
        GestMag_WINDOW.setTabOrder(self.tim_restTime, self.btn_addMaterial)
        GestMag_WINDOW.setTabOrder(self.btn_addMaterial, self.cmb_matID)
        GestMag_WINDOW.setTabOrder(self.cmb_matID, self.txt_blockID)
        GestMag_WINDOW.setTabOrder(self.txt_blockID, self.btn_genID)
        GestMag_WINDOW.setTabOrder(self.btn_genID, self.txt_dimX)
        GestMag_WINDOW.setTabOrder(self.txt_dimX, self.txt_dimY)
        GestMag_WINDOW.setTabOrder(self.txt_dimY, self.txt_dimZ)
        GestMag_WINDOW.setTabOrder(self.txt_dimZ, self.btn_addBlock)
        GestMag_WINDOW.setTabOrder(self.btn_addBlock, self.tableView)
        GestMag_WINDOW.setTabOrder(self.tableView, self.checkBox)
        GestMag_WINDOW.setTabOrder(self.checkBox, self.radioButton)
        GestMag_WINDOW.setTabOrder(self.radioButton, self.pushButton)

    def retranslateUi(self, GestMag_WINDOW):
        _translate = QtCore.QCoreApplication.translate
        GestMag_WINDOW.setWindowTitle(_translate("GestMag_WINDOW", "MainWindow"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_view), _translate("GestMag_WINDOW", "Storage"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_control), _translate("GestMag_WINDOW", "Control"))
        self.groupBox_2.setTitle(_translate("GestMag_WINDOW", "GroupBox"))
        self.groupBox_4.setTitle(_translate("GestMag_WINDOW", "GroupBox"))
        self.grp_material.setTitle(_translate("GestMag_WINDOW", "AddMaterial"))
        self.txt_lift.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_lift.setText(_translate("GestMag_WINDOW", "0"))
        self.label_8.setText(_translate("GestMag_WINDOW", "restTime"))
        self.label_6.setText(_translate("GestMag_WINDOW", "density"))
        self.tim_restTime.setDisplayFormat(_translate("GestMag_WINDOW", "HH:mm"))
        self.txt_color.setText(_translate("GestMag_WINDOW", "0"))
        self.label_7.setText(_translate("GestMag_WINDOW", "color"))
        self.label_5.setText(_translate("GestMag_WINDOW", "lift"))
        self.label_4.setText(_translate("GestMag_WINDOW", "Material_ID"))
        self.btn_addMaterial.setText(_translate("GestMag_WINDOW", "Add Material"))
        self.txt_matID.setText(_translate("GestMag_WINDOW", "AAA"))
        self.txt_density.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_density.setText(_translate("GestMag_WINDOW", "0"))
        self.grp_block.setTitle(_translate("GestMag_WINDOW", "AddBlock"))
        self.txt_blockID.setPlaceholderText(_translate("GestMag_WINDOW", "AAAA"))
        self.btn_genID.setText(_translate("GestMag_WINDOW", "Generate"))
        self.label.setText(_translate("GestMag_WINDOW", "Material_ID"))
        self.label_2.setText(_translate("GestMag_WINDOW", "Block_ID"))
        self.label_3.setText(_translate("GestMag_WINDOW", "Dimension X,Y,Z"))
        self.btn_addBlock.setText(_translate("GestMag_WINDOW", "Add Block"))
        self.txt_dimX.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimY.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimZ.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_manual), _translate("GestMag_WINDOW", "Manual"))
        self.checkBox.setText(_translate("GestMag_WINDOW", "CheckBox"))
        self.radioButton.setText(_translate("GestMag_WINDOW", "RadioButton"))
        self.pushButton.setText(_translate("GestMag_WINDOW", "PushButton"))

