# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GestMagUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GestMag_WINDOW(object):
    def setupUi(self, GestMag_WINDOW):
        GestMag_WINDOW.setObjectName("GestMag_WINDOW")
        GestMag_WINDOW.resize(964, 565)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GestMag_WINDOW.sizePolicy().hasHeightForWidth())
        GestMag_WINDOW.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(GestMag_WINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_mainWindow = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_mainWindow.setObjectName("tab_mainWindow")
        self.tab_view = QtWidgets.QWidget()
        self.tab_view.setObjectName("tab_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_view)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbl_storage = QtWidgets.QTableWidget(self.tab_view)
        self.tbl_storage.setObjectName("tbl_storage")
        self.tbl_storage.setColumnCount(0)
        self.tbl_storage.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tbl_storage)
        self.tab_mainWindow.addTab(self.tab_view, "")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_control)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_control)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_6.addWidget(self.comboBox, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setBaseSize(QtCore.QSize(100, 0))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_6.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.plainTextEdit.setAcceptDrops(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_control)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.btn_createStorage = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_createStorage.setObjectName("btn_createStorage")
        self.verticalLayout_3.addWidget(self.btn_createStorage)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tab_mainWindow.addTab(self.tab_control, "")
        self.tab_manual = QtWidgets.QWidget()
        self.tab_manual.setObjectName("tab_manual")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_manual)
        self.gridLayout.setObjectName("gridLayout")
        self.grp_block = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_block.setAlignment(QtCore.Qt.AlignCenter)
        self.grp_block.setObjectName("grp_block")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grp_block)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.grp_block)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.grp_block)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_blockID = QtWidgets.QLineEdit(self.grp_block)
        self.txt_blockID.setObjectName("txt_blockID")
        self.gridLayout_2.addWidget(self.txt_blockID, 1, 1, 1, 4)
        self.btn_genID = QtWidgets.QPushButton(self.grp_block)
        self.btn_genID.setObjectName("btn_genID")
        self.gridLayout_2.addWidget(self.btn_genID, 1, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_dimX = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimX.sizePolicy().hasHeightForWidth())
        self.txt_dimX.setSizePolicy(sizePolicy)
        self.txt_dimX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimX.setObjectName("txt_dimX")
        self.horizontalLayout_2.addWidget(self.txt_dimX)
        self.txt_dimY = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimY.sizePolicy().hasHeightForWidth())
        self.txt_dimY.setSizePolicy(sizePolicy)
        self.txt_dimY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimY.setObjectName("txt_dimY")
        self.horizontalLayout_2.addWidget(self.txt_dimY)
        self.txt_dimZ = QtWidgets.QLineEdit(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dimZ.sizePolicy().hasHeightForWidth())
        self.txt_dimZ.setSizePolicy(sizePolicy)
        self.txt_dimZ.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_dimZ.setObjectName("txt_dimZ")
        self.horizontalLayout_2.addWidget(self.txt_dimZ)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)
        self.btn_addBlock = QtWidgets.QPushButton(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addBlock.sizePolicy().hasHeightForWidth())
        self.btn_addBlock.setSizePolicy(sizePolicy)
        self.btn_addBlock.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addBlock.setObjectName("btn_addBlock")
        self.gridLayout_2.addWidget(self.btn_addBlock, 2, 3, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.grp_block)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 0, 1, 6)
        self.label_18 = QtWidgets.QLabel(self.grp_block)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.cmb_blockID = QtWidgets.QComboBox(self.grp_block)
        self.cmb_blockID.setMaxVisibleItems(10)
        self.cmb_blockID.setObjectName("cmb_blockID")
        self.gridLayout_2.addWidget(self.cmb_blockID, 4, 1, 1, 3)
        self.btn_delBlock = QtWidgets.QPushButton(self.grp_block)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delBlock.sizePolicy().hasHeightForWidth())
        self.btn_delBlock.setSizePolicy(sizePolicy)
        self.btn_delBlock.setBaseSize(QtCore.QSize(0, 0))
        self.btn_delBlock.setObjectName("btn_delBlock")
        self.gridLayout_2.addWidget(self.btn_delBlock, 4, 4, 1, 2)
        self.cmb_matID = QtWidgets.QComboBox(self.grp_block)
        self.cmb_matID.setMaxVisibleItems(10)
        self.cmb_matID.setObjectName("cmb_matID")
        self.gridLayout_2.addWidget(self.cmb_matID, 0, 1, 1, 5)
        self.gridLayout.addWidget(self.grp_block, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_manual)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.txt_orderID = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_orderID.setObjectName("txt_orderID")
        self.gridLayout_5.addWidget(self.txt_orderID, 0, 1, 1, 3)
        self.btn_genID2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_genID2.setObjectName("btn_genID2")
        self.gridLayout_5.addWidget(self.btn_genID2, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.txt_customer = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_customer.setObjectName("txt_customer")
        self.gridLayout_5.addWidget(self.txt_customer, 1, 1, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 1, 3, 1, 1)
        self.cmb_recipeID2 = QtWidgets.QComboBox(self.groupBox_4)
        self.cmb_recipeID2.setObjectName("cmb_recipeID2")
        self.gridLayout_5.addWidget(self.cmb_recipeID2, 1, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.dat_deliveryDate = QtWidgets.QDateEdit(self.groupBox_4)
        self.dat_deliveryDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dat_deliveryDate.setObjectName("dat_deliveryDate")
        self.gridLayout_5.addWidget(self.dat_deliveryDate, 2, 1, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 3, 0, 1, 1)
        self.spn_nPieces = QtWidgets.QSpinBox(self.groupBox_4)
        self.spn_nPieces.setObjectName("spn_nPieces")
        self.gridLayout_5.addWidget(self.spn_nPieces, 3, 1, 1, 1)
        self.btn_addOrder = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_addOrder.setObjectName("btn_addOrder")
        self.gridLayout_5.addWidget(self.btn_addOrder, 3, 2, 1, 3)
        self.line_4 = QtWidgets.QFrame(self.groupBox_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 4, 0, 1, 5)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 5, 0, 1, 1)
        self.cmb_orderID = QtWidgets.QComboBox(self.groupBox_4)
        self.cmb_orderID.setObjectName("cmb_orderID")
        self.gridLayout_5.addWidget(self.cmb_orderID, 5, 1, 1, 2)
        self.btn_delOrder = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_delOrder.setObjectName("btn_delOrder")
        self.gridLayout_5.addWidget(self.btn_delOrder, 5, 3, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.grp_material = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_material.setAlignment(QtCore.Qt.AlignCenter)
        self.grp_material.setObjectName("grp_material")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grp_material)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.txt_matID = QtWidgets.QLineEdit(self.grp_material)
        self.txt_matID.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_matID.setInputMask("")
        self.txt_matID.setMaxLength(32767)
        self.txt_matID.setPlaceholderText("")
        self.txt_matID.setObjectName("txt_matID")
        self.gridLayout_3.addWidget(self.txt_matID, 0, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.grp_material)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.txt_lift = QtWidgets.QLineEdit(self.grp_material)
        self.txt_lift.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_lift.setPlaceholderText("")
        self.txt_lift.setObjectName("txt_lift")
        self.gridLayout_3.addWidget(self.txt_lift, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grp_material)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.tim_restTime = QtWidgets.QTimeEdit(self.grp_material)
        self.tim_restTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tim_restTime.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.tim_restTime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.tim_restTime.setCalendarPopup(False)
        self.tim_restTime.setObjectName("tim_restTime")
        self.gridLayout_3.addWidget(self.tim_restTime, 4, 1, 1, 1)
        self.txt_density = QtWidgets.QLineEdit(self.grp_material)
        self.txt_density.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_density.setPlaceholderText("")
        self.txt_density.setObjectName("txt_density")
        self.gridLayout_3.addWidget(self.txt_density, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grp_material)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 3, 0, 1, 1)
        self.txt_color = QtWidgets.QLineEdit(self.grp_material)
        self.txt_color.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_color.setMaxLength(10)
        self.txt_color.setPlaceholderText("")
        self.txt_color.setObjectName("txt_color")
        self.gridLayout_3.addWidget(self.txt_color, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.grp_material)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 4, 0, 1, 1)
        self.btn_addMaterial = QtWidgets.QPushButton(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addMaterial.sizePolicy().hasHeightForWidth())
        self.btn_addMaterial.setSizePolicy(sizePolicy)
        self.btn_addMaterial.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addMaterial.setObjectName("btn_addMaterial")
        self.gridLayout_3.addWidget(self.btn_addMaterial, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 0, 1, 1)
        self.cmb_matID2 = QtWidgets.QComboBox(self.grp_material)
        self.cmb_matID2.setMaxVisibleItems(10)
        self.cmb_matID2.setObjectName("cmb_matID2")
        self.gridLayout_3.addWidget(self.cmb_matID2, 6, 1, 1, 1)
        self.btn_delMaterial = QtWidgets.QPushButton(self.grp_material)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delMaterial.sizePolicy().hasHeightForWidth())
        self.btn_delMaterial.setSizePolicy(sizePolicy)
        self.btn_delMaterial.setBaseSize(QtCore.QSize(0, 0))
        self.btn_delMaterial.setObjectName("btn_delMaterial")
        self.gridLayout_3.addWidget(self.btn_delMaterial, 6, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.grp_material)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 3)
        self.gridLayout.addWidget(self.grp_material, 0, 0, 1, 1)
        self.grp_recipe = QtWidgets.QGroupBox(self.tab_manual)
        self.grp_recipe.setAlignment(QtCore.Qt.AlignCenter)
        self.grp_recipe.setObjectName("grp_recipe")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grp_recipe)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cmb_cncProg = QtWidgets.QComboBox(self.grp_recipe)
        self.cmb_cncProg.setMaxVisibleItems(10)
        self.cmb_cncProg.setObjectName("cmb_cncProg")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.cmb_cncProg.addItem("")
        self.gridLayout_4.addWidget(self.cmb_cncProg, 3, 2, 1, 1)
        self.txt_nCutOriz = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_nCutOriz.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_nCutOriz.setMaxLength(3)
        self.txt_nCutOriz.setPlaceholderText("")
        self.txt_nCutOriz.setObjectName("txt_nCutOriz")
        self.gridLayout_4.addWidget(self.txt_nCutOriz, 2, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.grp_recipe)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 5, 0, 1, 8)
        self.label_13 = QtWidgets.QLabel(self.grp_recipe)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.grp_recipe)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grp_recipe)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 4, 1, 1)
        self.txt_nCutVert = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_nCutVert.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_nCutVert.setMaxLength(3)
        self.txt_nCutVert.setPlaceholderText("")
        self.txt_nCutVert.setObjectName("txt_nCutVert")
        self.gridLayout_4.addWidget(self.txt_nCutVert, 1, 1, 1, 3)
        self.txt_spCutVert = QtWidgets.QLineEdit(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_spCutVert.sizePolicy().hasHeightForWidth())
        self.txt_spCutVert.setSizePolicy(sizePolicy)
        self.txt_spCutVert.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_spCutVert.setMaxLength(3)
        self.txt_spCutVert.setPlaceholderText("")
        self.txt_spCutVert.setObjectName("txt_spCutVert")
        self.gridLayout_4.addWidget(self.txt_spCutVert, 1, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.grp_recipe)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 7, 0, 1, 1)
        self.txt_spCutOriz = QtWidgets.QLineEdit(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_spCutOriz.sizePolicy().hasHeightForWidth())
        self.txt_spCutOriz.setSizePolicy(sizePolicy)
        self.txt_spCutOriz.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_spCutOriz.setMaxLength(3)
        self.txt_spCutOriz.setPlaceholderText("")
        self.txt_spCutOriz.setObjectName("txt_spCutOriz")
        self.gridLayout_4.addWidget(self.txt_spCutOriz, 2, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.cmb_recipeID = QtWidgets.QComboBox(self.grp_recipe)
        self.cmb_recipeID.setObjectName("cmb_recipeID")
        self.gridLayout_4.addWidget(self.cmb_recipeID, 7, 2, 1, 1)
        self.btn_delRecipe = QtWidgets.QPushButton(self.grp_recipe)
        self.btn_delRecipe.setObjectName("btn_delRecipe")
        self.gridLayout_4.addWidget(self.btn_delRecipe, 7, 4, 1, 4)
        self.label_27 = QtWidgets.QLabel(self.grp_recipe)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        self.txt_execOrder = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_execOrder.setObjectName("txt_execOrder")
        self.gridLayout_4.addWidget(self.txt_execOrder, 4, 2, 1, 1)
        self.btn_addRecipe = QtWidgets.QPushButton(self.grp_recipe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addRecipe.sizePolicy().hasHeightForWidth())
        self.btn_addRecipe.setSizePolicy(sizePolicy)
        self.btn_addRecipe.setBaseSize(QtCore.QSize(0, 0))
        self.btn_addRecipe.setObjectName("btn_addRecipe")
        self.gridLayout_4.addWidget(self.btn_addRecipe, 4, 4, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.grp_recipe)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 4, 1, 1)
        self.cmb_matID3 = QtWidgets.QComboBox(self.grp_recipe)
        self.cmb_matID3.setMaxVisibleItems(10)
        self.cmb_matID3.setObjectName("cmb_matID3")
        self.gridLayout_4.addWidget(self.cmb_matID3, 3, 7, 1, 1)
        self.txt_rcpID = QtWidgets.QLineEdit(self.grp_recipe)
        self.txt_rcpID.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_rcpID.setInputMask("")
        self.txt_rcpID.setMaxLength(32767)
        self.txt_rcpID.setObjectName("txt_rcpID")
        self.gridLayout_4.addWidget(self.txt_rcpID, 0, 2, 1, 4)
        self.gridLayout.addWidget(self.grp_recipe, 1, 0, 1, 1)
        self.tab_mainWindow.addTab(self.tab_manual, "")
        self.horizontalLayout.addWidget(self.tab_mainWindow)
        GestMag_WINDOW.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GestMag_WINDOW)
        self.statusbar.setObjectName("statusbar")
        GestMag_WINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(GestMag_WINDOW)
        self.tab_mainWindow.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(GestMag_WINDOW)
        GestMag_WINDOW.setTabOrder(self.cmb_matID, self.txt_blockID)
        GestMag_WINDOW.setTabOrder(self.txt_blockID, self.btn_genID)
        GestMag_WINDOW.setTabOrder(self.btn_genID, self.txt_dimX)
        GestMag_WINDOW.setTabOrder(self.txt_dimX, self.txt_dimY)

    def retranslateUi(self, GestMag_WINDOW):
        _translate = QtCore.QCoreApplication.translate
        GestMag_WINDOW.setWindowTitle(_translate("GestMag_WINDOW", "MainWindow"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_view), _translate("GestMag_WINDOW", "Storage"))
        self.groupBox.setTitle(_translate("GestMag_WINDOW", "CNC"))
        self.label_25.setText(_translate("GestMag_WINDOW", "CNC List"))
        self.pushButton.setText(_translate("GestMag_WINDOW", "Load"))
        self.label_26.setText(_translate("GestMag_WINDOW", "Order"))
        self.pushButton_2.setText(_translate("GestMag_WINDOW", "Unload"))
        self.pushButton_3.setText(_translate("GestMag_WINDOW", "GetStatus"))
        self.groupBox_2.setTitle(_translate("GestMag_WINDOW", "STORAGE"))
        self.btn_createStorage.setText(_translate("GestMag_WINDOW", "CreateStorage"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_control), _translate("GestMag_WINDOW", "Control"))
        self.grp_block.setTitle(_translate("GestMag_WINDOW", "BLOCKS"))
        self.label.setText(_translate("GestMag_WINDOW", "Material ID"))
        self.label_2.setText(_translate("GestMag_WINDOW", "Block ID"))
        self.txt_blockID.setPlaceholderText(_translate("GestMag_WINDOW", "AAAA"))
        self.btn_genID.setText(_translate("GestMag_WINDOW", "Generate"))
        self.label_3.setText(_translate("GestMag_WINDOW", "Dimension X,Y,Z"))
        self.txt_dimX.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimY.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.txt_dimZ.setPlaceholderText(_translate("GestMag_WINDOW", "0"))
        self.btn_addBlock.setText(_translate("GestMag_WINDOW", "Add Block"))
        self.label_18.setText(_translate("GestMag_WINDOW", "Block ID"))
        self.btn_delBlock.setText(_translate("GestMag_WINDOW", "Del Block"))
        self.groupBox_4.setTitle(_translate("GestMag_WINDOW", "ORDERS"))
        self.label_19.setText(_translate("GestMag_WINDOW", "Order ID"))
        self.txt_orderID.setText(_translate("GestMag_WINDOW", "order"))
        self.btn_genID2.setText(_translate("GestMag_WINDOW", "Generate"))
        self.label_20.setText(_translate("GestMag_WINDOW", "Customer"))
        self.txt_customer.setText(_translate("GestMag_WINDOW", "customer"))
        self.label_22.setText(_translate("GestMag_WINDOW", "Recipe ID"))
        self.label_21.setText(_translate("GestMag_WINDOW", "Delivery Date"))
        self.label_23.setText(_translate("GestMag_WINDOW", "N# Pieces"))
        self.btn_addOrder.setText(_translate("GestMag_WINDOW", "Add Order"))
        self.label_24.setText(_translate("GestMag_WINDOW", "Order ID"))
        self.btn_delOrder.setText(_translate("GestMag_WINDOW", "Delete Order"))
        self.grp_material.setTitle(_translate("GestMag_WINDOW", "MATERIALS"))
        self.label_4.setText(_translate("GestMag_WINDOW", "Material ID"))
        self.txt_matID.setText(_translate("GestMag_WINDOW", "material"))
        self.label_5.setText(_translate("GestMag_WINDOW", "Lift"))
        self.txt_lift.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_lift.setText(_translate("GestMag_WINDOW", "0"))
        self.label_6.setText(_translate("GestMag_WINDOW", "Density"))
        self.tim_restTime.setDisplayFormat(_translate("GestMag_WINDOW", "HH:mm"))
        self.txt_density.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_density.setText(_translate("GestMag_WINDOW", "0"))
        self.label_7.setText(_translate("GestMag_WINDOW", "Color"))
        self.txt_color.setText(_translate("GestMag_WINDOW", "0"))
        self.label_8.setText(_translate("GestMag_WINDOW", "Rest Time"))
        self.btn_addMaterial.setText(_translate("GestMag_WINDOW", "Add Material"))
        self.label_17.setText(_translate("GestMag_WINDOW", "Material ID"))
        self.btn_delMaterial.setText(_translate("GestMag_WINDOW", "Delete Material"))
        self.grp_recipe.setTitle(_translate("GestMag_WINDOW", "RECIPES"))
        self.cmb_cncProg.setItemText(0, _translate("GestMag_WINDOW", "NULL"))
        self.cmb_cncProg.setItemText(1, _translate("GestMag_WINDOW", "FIOR"))
        self.cmb_cncProg.setItemText(2, _translate("GestMag_WINDOW", "OZARI"))
        self.cmb_cncProg.setItemText(3, _translate("GestMag_WINDOW", "OKIN"))
        self.cmb_cncProg.setItemText(4, _translate("GestMag_WINDOW", "CULL"))
        self.cmb_cncProg.setItemText(5, _translate("GestMag_WINDOW", "LOCH"))
        self.cmb_cncProg.setItemText(6, _translate("GestMag_WINDOW", "GALT"))
        self.txt_nCutOriz.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_nCutOriz.setText(_translate("GestMag_WINDOW", "0"))
        self.label_12.setText(_translate("GestMag_WINDOW", "N# H Cut"))
        self.label_13.setText(_translate("GestMag_WINDOW", "Thk Hcut"))
        self.label_14.setText(_translate("GestMag_WINDOW", "CNC Prog"))
        self.label_10.setText(_translate("GestMag_WINDOW", "N# V Cut"))
        self.label_11.setText(_translate("GestMag_WINDOW", "Thk Vcut"))
        self.txt_nCutVert.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_nCutVert.setText(_translate("GestMag_WINDOW", "0"))
        self.txt_spCutVert.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_spCutVert.setText(_translate("GestMag_WINDOW", "0"))
        self.label_16.setText(_translate("GestMag_WINDOW", "Recipe ID"))
        self.txt_spCutOriz.setInputMask(_translate("GestMag_WINDOW", "000"))
        self.txt_spCutOriz.setText(_translate("GestMag_WINDOW", "0"))
        self.label_15.setText(_translate("GestMag_WINDOW", "Recipe ID"))
        self.btn_delRecipe.setText(_translate("GestMag_WINDOW", "Delete Recipe"))
        self.label_27.setText(_translate("GestMag_WINDOW", "Exec Order"))
        self.txt_execOrder.setToolTip(_translate("GestMag_WINDOW", "<html><head/><body><p>V: vertical </p><p>O: orizzontal </p><p>P: program</p><p>n: null</p><p>example: V,P,n</p></body></html>"))
        self.txt_execOrder.setInputMask(_translate("GestMag_WINDOW", "A,A,A"))
        self.btn_addRecipe.setText(_translate("GestMag_WINDOW", "Add Recipe"))
        self.label_9.setText(_translate("GestMag_WINDOW", "Material ID"))
        self.txt_rcpID.setText(_translate("GestMag_WINDOW", "recipe"))
        self.tab_mainWindow.setTabText(self.tab_mainWindow.indexOf(self.tab_manual), _translate("GestMag_WINDOW", "Manual"))

